### ISSUE TITLE
What is offline and how can it make my life betterer?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-offline-first#1]
- http://diveintohtml5.info/offline.html
- https://github.com/pazguille/offline-first
- http://offlinefirst.org/

**Comment by ZooeyMiller** [comment]
@finnhodgkin and I are looking through resources for offline first to be listed in this comment :sparkles: 

Info on offline-first on iphone: https://www.thecssninja.com/css/how-to-create-offline-webapps-on-the-iphone
Apple docs on application cache: https://developer.apple.com/library/content/documentation/iPhone/Conceptual/SafariJSDatabaseGuide/OfflineApplicationCache/OfflineApplicationCache.html
localForage repo for using offline storage options available in your browser with one api: https://github.com/localForage/localForage

Google information on service workers: https://developers.google.com/web/fundamentals/getting-started/primers/service-workers (service workers make offline first really nice in chrome/firefox/opera but aren't in safari :frowning: )
SW precache is a great node module for generating service workers: https://github.com/GoogleChrome/sw-precache

Extra information on using the applicationcache: https://www.html5rocks.com/en/tutorials/appcache/beginner/

**Comment by ZooeyMiller** [comment]
@nelsonic we've started working on an example (#4) to use the info we're learning about offline first apps, we're having some trouble with some of the features related to safari, do you think we should prioritise getting something working, or collating resources and getting some kind of readme in place?

**Comment by nelsonic** [comment]
@ZooeyMiller I tend to do "Readme-Driven-Development" as much as possible, i.e. document the learning `while` doing/building the example. If you document `after` then you are more likely to forget/skip details.

**Comment by nelsonic** [comment]
@ZooeyMiller & @finnhodgkin great work! 👍
