### ISSUE TITLE
Add learnings about testing with JSDOM to readme

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-offline-first#11]
We need to add our learnings about how to test this code with JSDOM #9 to the readme so that people reading it can learn how to do it too.

**Comment by finnhodgkin** [comment]
Should all our test findings go directly in the learn-offline-first readme or just the issues? 

I can see the relevance of stuff directly related to testing offline-specific things, but isn't general JSDOM stuff a little off topic?  

For the time being I'll pop them in here.

**Comment by ZooeyMiller** [comment]
@nelsonic any thoughts on whether this info should be in the readme or just in the issues?

**Comment by nelsonic** [comment]
@ZooeyMiller definitely needs to be in a readme. (_please/thanks!_)

I _actually_ think it's worth adding a new Markdown file in https://github.com/dwyl/learn-tdd
or https://github.com/dwyl/learn-tape (_which is more server-focussed_)

"How to test front-end code on the server using Tape".

**Comment by ZooeyMiller** [comment]
@nelsonic
Awesome, in which case, I'm going to raise a issue to add findings from here to a .md file in https://github.com/dwyl/learn-tape and close this issue if that's okay? 
Maybe once we've completed the "How to test front-end code on the server using Tape" file for learn-tape we can link to it from here to show how we've tested the stuff in this repo.

**Comment by nelsonic** [comment]
@sounds good. feel free to close. I've added you as colab to `learn-tape` 👍

**Comment by ZooeyMiller** [comment]
perfect :+1: done.
