### ISSUE TITLE
Add tests to example.

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-offline-first#9]
We need to add tests to our example to make sure it is reliable.

testing some of the functionality will be okay, but the online/offline stuff may be a little more difficult so we need to explore.

EDIT: JSDOM does have `window.navigator.onLine` boolean, and seems to have `offline`/`online` events on the window as well, but I'm not sure how to change them or get the `offline`/`online` events to fire.
If we try to hard code  `window.navigator.onLine` to false it is changed back to true by JSDOM, and it _always_ returns true, even when the machine is offline. Doing more googling to try and find a way without having to learn Sinon. 

It seems that even though JSDOM does have `window.navigator.onLine` it is read-only [(see this code snippet)](https://github.com/tmpvar/jsdom/blob/a6acac4e9dec4f859fff22676fb4e9eaa9139787/lib/jsdom/living/navigator/Navigator.idl#L33-L36). It is also automatically set to `true` by the implementation. Not sure how to change it when it's [declared like this.](https://github.com/tmpvar/jsdom/blob/a6acac4e9dec4f859fff22676fb4e9eaa9139787/lib/jsdom/living/navigator/NavigatorOnLine-impl.js) No idea how the `offline`/`online` events can fire when `window.navigator.onLine` is always set to true.

**Comment by nelsonic** [comment]
We need to mock the browser API to _simulate_ testing.
We _could_ use `JSDOM` for this https://github.com/tmpvar/jsdom
and https://github.com/lmaccherone/node-localstorage to achieve this.
see: https://github.com/dwyl/learn-elm-architecture-in-javascript/blob/master/test/test.js

**Comment by ZooeyMiller** [comment]
We're working on spiking on how to test local storage and such this morning for 4hr, then will continue to start testing from there, will document findings in this issue.

**Comment by ZooeyMiller** [comment]
We're having some trouble with JSDOM as in our JS [we declare some global variables](https://github.com/dwyl/learn-offline-first/blob/master/example/public/script.js#L4-L6) which get the elements we need from the DOM. When we require this in in node we have problems because `document` is not defined. 
We run an init function in our test file, but this is not early enough as those declarations are evaluated when we require the JS file in. 

EDIT: 
We've remedied this by putting the declaration of the variables and the attachment of the event listeners into a function, which is then called in a script tag in the index.html. This gets around node evaluating the variables and event listeners and means that we can actually test our front end code with node.

**Comment by samhstn** [comment]
@ZooeyMiller could you look at adding a line to the top of that file which is something like:

```javascript
var document = document || (new JSDOM(`...`)).window.document;
```

**Comment by ZooeyMiller** [comment]
JSDOM does not support `innerText` but does support `textContent` so if using it, make sure that your code uses `textContent` (this cause us a bit of trouble)
